### PR TITLE
Modularized version of DTedit

### PR DESCRIPTION
**Pull request by DavidPatShuiFong**
Modularized version of DTedit

Main added feature is addition of *input.types* with dynamically changing selections  (**selectInputReactive** and **selectInputMultipleReactive**). dtedit (optionally) accepts a *reactive* dataframe, and will update the internal copy of the data if the 'external' dataframe changes.

Added simple example `example(dtedit)` and extensively changed dtedit_demo() to demonstrate new features.

Some minor bug-fixes and improvements such as the ability to handle single-column tables (by strategically adding `drop = FALSE`) and addition of error-handling to `callback.delete`.

Numerous comments added, admittedly mostly for my own education.

### CODE REVIEW

**Comment by andresrcs** [comment]
> dtedit (optionally) accepts a reactive dataframe, and will update the internal copy of the data if the 'external' dataframe changes.

This would be a really nice feature indeed, any chance you could add a simple vignette for this functionality?

**Comment by DavidPatShuiFong** [comment]
> 
> 
> > dtedit (optionally) accepts a reactive dataframe, and will update the internal copy of the data if the 'external' dataframe changes.
> 
> This would be a really nice feature indeed, any chance you could add a simple vignette for this functionality?

There is a demonstration in dtedit_demo() with the email list. I've just added a slightly simpler example, which can be found in `inst/examples/example_reactivedataframe.R`. Alternatively, if my modified version of **DTEdit** is installed, the example can be seen in the documentation `?dteditUI`.

**Comment by DavidPatShuiFong** [comment]
Hmmmm, there might be some strange library version dependencies in the version of DTedit I have created. It works on all three Windows installations (Microsoft R Open, which uses some sort of standardized nine-month old library archive MRAN), but only works properly on one Linux system I have tried (out of three).

For some reason, when using Ubuntu (Bionic Beaver LTS 18.04.2) and openSuSE LEAP 15.0 the DT tables just won't update their display of data. Strangely, on another one of my installations of openSuSE LEAP 15.0, everything does work! The original dtedit as done by Bryer works when my version does not. Difficult to know where the problem lies, library versions on my Linux systems could both be older and newer than what is available on MRAN.

**Comment by DavidPatShuiFong** [comment]
The problem appears to be with **DT**, with release `0.5`, the [bug is referenced in "Fix bug where replaceData doesn't work in Shiny modules"](https://github.com/rstudio/DT/pull/628).

So, this set of code works in **DT** version `0.4`, but not version `0.5`. It *does* work with current **DT** development version `0.5.3`.

**Comment by jbryer** [comment]
Any idea when a new version of DT will be submitted to CRAN? I am hoping to
look into your pull request soon (semester is coming to an end so will have
some time to work on this). However, if it is not compatible with the
current CRAN version of DT, not sure it is worth the effort.

**Comment by DavidPatShuiFong** [comment]
Version 0.6.0 (which incorporates the required fixes to make a 'modularized' version of DTedit work) was accepted into CRAN a few days ago!

Though I'm wondering if I should modify the code to make it fully backward compatible with the current version of DTedit. Since this pull request re-defines 'dtedit' into a not fully-compatible version.

**Comment by jbryer** [comment]
Thanks for the update. I was thinking of renaming your function to
something like DTeditMod so that both versions can live together in the
package. The common code could be refactored out from there.

**Comment by DavidPatShuiFong** [comment]
Also thought that renaming the modularized functions was the best way to go! Though one of the functions would need a '-`UI`' tag, so I think `DTeditModUI` would be quite a mouthful! Though more cryptic, perhaps just `dteditm` and `dteditmUI`?

There is considerable amount of common code, although refactoring out would change the visual structure of the code quite significantly.

**Comment by soetang** [comment]
Hey

Looks like a very cool update as working with shiny modules is essential to our workflow.

Is there a timeline for this? and what is needed to make this happen? If the work is not too heavy i might be able to help.

**Comment by DavidPatShuiFong** [comment]
Thanks Benjamin!

I wish there was a timeline to 'factor' out the common code and have DTedit and 'module' version of DTedit to live side-by-side!

Unfortunately, I am actually using 'DTedit' (modularized) in production and _it works for me_. Since that project has rather more people 'I actually meet in real life' making requests for changes (and I am still lobbying to use that software in my own workplace), that project takes priority for me.

Sorry! It is on my list of 'things to do', just not at the top of the list....

> Hey
> 
> Looks like a very cool update. Working with shiny modules is essential to our workflow.
> 
> Is there a timeline for this? and what is needed to make this happen? If the work is not too heavy i might be able to help.

**Comment by DavidPatShuiFong** [comment]
I've done it! 

`dtedit` is now operates, I believe, compatibly with your version 1.0.0 of `dtedit`, but with various improved functionality and bugfixes (and perhaps new bugs of my own making...)

I have rename the modularized version to `dteditmod` and `dteditmodUI`, breaking compatibility with my previous modularized version of `dtedit`, but such is life. That is not the only change, I have also changed the `thedataframe` option to `thedata` in the modularized version, to make that consistent with the non-modular version.

`dtedit` is just a few lines of code, which calls `dteditmod` and shoe-horns the as.character option `name` into `dteditmod`'s `session`. `dteditmod`, in a very hack-ish fashion, recognizes that `session` is not an environment, and adjusts its variables accordingly.

I have taken the liberty of upgrading the version number to 2 and adding my name 😊 to the Author list...

Other compatibility and debatable changes compared to v1.0.0 `dtedit`

- the returned list only contains `$thedata` and `$edit.count`. I'm not sure what the purpose of returning `$edit.cols` and `$view.cols` is. I suppose they can be added back in...
- I changed the formatting to tidyverse/styler style

David

**Comment by DavidPatShuiFong** [comment]
Thanks, it's a long weekend here in Australia (Queen's Birthday) and too cold to go outside, so I have completed as much as I want to do? Though I should ask what kind of changes you were looking for?

My most recent changes have sought to improve inter-operability with the non-module version of `dtedit`. As a result the modular versions have been renamed `dteditmod` and `dteditmodUI`, and the `thedataframe` option has been renamed `thedata`.

New features include `fileSelect`, support for binary blob columns and action buttons.
 
> 
> Hey
> 
> Looks like a very cool update. Working with shiny modules is essential to our workflow.
> 
> Is there a timeline for this? and what is needed to make this happen? If the work is not too heavy i might be able to help.

**Comment by DavidPatShuiFong** [comment]
> 
> 
> > dtedit (optionally) accepts a reactive dataframe, and will update the internal copy of the data if the 'external' dataframe changes.
> 
> This would be a really nice feature indeed, any chance you could add a simple vignette for this functionality?

I've added many, many more examples, improved the '?' help and updated the README.md

Is there a particular pattern of vignette you have in mind?
Unfortunately, for a shiny app, a vignette might not be very interactive :(

Let me know if I can be of further assistance!

**Comment by DavidPatShuiFong** [comment]
> I was wondering - can you pass a reactive dataframe to dtedit now? e.g.
> 
> ```
> samplesData<-reactive({ 
> 
> code_to_make_a_dataframe
> })
> 
> dtedit(input, output,
> 
>          name = 'samples',
>          thedata = samplesData(),
> ...
> ```
> 
> I have tried this but can't get the table to update. I need the ability for the user to select part of the table from a dropdown elsewhere in my app; the dtedit() table then updates just those matching records (for the user to edit at their leisure).
> 
> Thanks!

Thanks @simon-tarr . If reactivity is desired, then the reactive needs to be passed without the trailing braces `()`, just `samplesData`. In other languages, I think that would be called passing by reference!

There are examples at :

https://github.com/DavidPatShuiFong/DTedit/blob/master/inst/shiny_demo/app_reactivedataframe.R

and a new [vignette](https://rpubs.com/DavidFong/DTedit) on my [develop branch](https://github.com/DavidPatShuiFong/DTedit/tree/develop):

**Comment by simon-tarr** [comment]
It sure does! Thank you for the reply!

**Comment by DavidPatShuiFong** [comment]
Considerable improvement in documentation and self-testing (using testthat/shinytest).

Vignette available 'in-package', and can also be seen on [RPubs](https://rpubs.com/DavidFong/DTedit).
[Code coverage at 98% ](https://codecov.io/gh/DavidPatShuiFong/DTedit?branch=master) 😄

**Comment by DavidPatShuiFong** [comment]
The return value of `dtedit`/`dteditmod` `v2.0.x` was not the same (/incompatible) with the original version of `dtedit`. This has now been fixed. The return value is a `reactiveValues`, e.g containing $thedata, and is *not* a list of reactives. This release version `v2.1.0` is *not* completely compatible with `v2.0.x` for this reason.

New feature - added parameters for save/cancel buttons and delete modal dialog. Thanks @cocinerox !

An earlier thank you to @klodiandhana for fixing a bug `selectInput`!

**Comment by DavidPatShuiFong** [comment]
New features/changes (release 2.2.0)

* Allow definition of which data columns are displayed in the delete dialog, and how those columns are labelled.
  + `delete.info.cols` and `delete.info.label.cols`
  + written by László Szakács (@cocinerox), thanks!
* Allow display of rownames.
  + `datatable.rownames`. By default, set to FALSE. If set to TRUE, then row names are also displyaed in edit and update modal dialogs. datatable.rownames must be set to TRUE is using DT::format*() functions in datatable.call.
* Allow changes in the transfer of data to `DT::renderDataTable`
  + datatable.call For example this allows the use of DT::format*() functions.
  + 'under the hood' there is a significant change in the way DT::renderDataTable is called. This is a breaking change, some uses of `dtedit` which use `datatable.options` will not work without change.

**Comment by DavidPatShuiFong** [comment]
New features (release 2.2.1)

* Custom icons for Add/Edit/Delete/Copy buttons
   + icon.delete, icon.edit, icon.add and icon.copy
   + by László Szakács (@cocinerox ), after @vwrobel
* error messages, e.g. generated by callback.insert, can have HTML
   + by László Szakács (@cocinerox )

**Comment by ramnathv** [comment]
This is a really cool addition to the package. @jbryer Any idea when this would be merged to master?

**Pull request merged**
